### PR TITLE
FAQ updates

### PR DESCRIPTION
**Pull request by brson**
This contains a variety of changes from a full pass over the FAQ.

### CODE REVIEW

**Comment by brson** [comment]
Here are my notes about problems I still have with this. We don't need to address this now, just noting it for future reference.

* Ord / Eq problem is not clear
* How can I understand the borrow checker is kinda unfulfilling - if it was that easy everyone would get it
* How do deref coercions work doesn't actually explain it but links to the book
* How do I return a borrow to something I created from a function - does not give a very actionable answer. Needs examples
* When are lifetimes required to be defined, explains the answer in terms of when they are not required. This answer should be structured to not just repeat the elision rules
* HKT explanation doesn't explain anything to me:
  - "higher-kinded types are types that take other types as parameters" sounds like generics
  - "Type constructors, like `Vec` are examples" - if Vec is an HKT then why doesn't Rust have HKT? What's a type constructor?
  - the example introduces new syntax but doesn't explain which is the new syntax and what it means
* Why doesn't Rust have exceptions? This needs to be more convincing. Especially 'they interoperate poorly with multithreaded code'.
* Can I use static values across threads without an `unsafe` block?
  - I don't understand this question or answer -`'static` declarations can be accessed anywhere.
* What is the relationship between a module and a crate?
  - "Crates do not have global names, only a set of non-unique metadata tags." does not make sense to me
* Does Rust allow non-constant-expression values for globals?
  - why is it ok for thread_local! to have non-static initialization but not for statics? they both have initialization order problems? does this just distract from the main point

**Comment by brson** [comment]
Another point we need to consider. This draft no longer tries to answer the question 'What does the name Rust mean?'. While I think we need to not promote the fungus idea, it is a FAQ and probably should be tackled.

**Comment by AndrewBrinker** [comment]
Okay. Except for a few typos, this looks good. I'm going to merge it, fix the typos, and then go over the suggestions you made above.

**Comment by AndrewBrinker** [comment]
Okay, so here are my thoughts on the problems you outlined above:

1. The Ord / Eq problem

We currently have two questions about Eq vs. PartialEq and Ord vs. PartialOrd, but you're right that neither tackles it directly. I'll go ahead and add a more direct question / answer for this.

2. Understanding the borrow checker

You're right that the question makes it seem simpler than it usually is in practice. In my experience, most of the problems from the borrow checker come from two issues: 1) how to avoid multiple mutable references, 2) how to get the lifetimes of your borrows correct. I'll go ahead and expand the answer to clarify that although the rules are simple, the program design implications are more complicated than expected, particularly since programmers new to Rust are often unaccustomed to considering lifetimes and borrows explicitly.

3. Deref corcions

You're right. I'll expand the answer.

4. Returning borrows to things created in functions

Same.

5. Lifetime elision rules

I'll take a swing at rewriting the answer. I wouldn't be surprised if it takes a couple drafts to get right.

6. Higher kinded types

You're right. I've rewritten the answer to clarify the points of confusion.

7. Exceptions

I'll work on this.

8. Static values across threads

The question is specifically about variables declared with the `static` keyword, not references with the `'static` lifetime, which should be clarified.

9. Crates vs. Modules

I believe this answer was copied over from an older document. I'll clean it up.

**Comment by brson** [comment]
@AndrewBrinker thanks for addressing my comments here! I wasn't even expecting you too since these are some of the hardest FAQs. We'll get the core team to review and deploy soon.

**Comment by AndrewBrinker** [comment]
Sounds good! I'll swing back around to the remaining suggestions (and I have some changes of my own in mind too) after the initial document is published. Thanks for all the help during this process.

**Pull request merged**
